Name: zerocmf
Host: 0.0.0.0
Port: 8080

# mysql配置
Mysql:
  Host: localhost
  Database: zerocmf
  Username: root
  Password: "123456"
  Port: 3306
  Charset: utf8mb4
  Prefix: cmf_
  AuthCode: KFHlk2ubIlMr5ltqaD

# redis配置
Redis:
  Enabled: true
  Addr: localhost:6379
  DB: 0
  Password: ""

# 短信配置
Sms:
  AccessKeyId: 111
  AccessKeySecret: 111
  Provider: ali
  SignName: 码上云
  TemplateCode: SMS_203678233
