// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"zerocmf/configs"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp(config configs.Config) *ServiceContext {
	serviceContext := newApp(config)
	return serviceContext
}
