// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"zerocmf/configs"
	"zerocmf/internal/biz"
	"zerocmf/internal/data"
	"zerocmf/internal/server"
	"zerocmf/internal/service"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp(config *configs.Config) (App, func(), error) {
	dataData, cleanup, err := data.NewData(config)
	if err != nil {
		return App{}, nil, err
	}
	testRepo := data.NewTestRepo(dataData)
	testUsecase := biz.NewTestUsecase(testRepo)
	testService := service.NewTestService(testUsecase)
	engine := server.NewHTTPServer(config, testService)
	app := newApp(engine)
	return app, func() {
		cleanup()
	}, nil
}
